"""empty message

Revision ID: 0a9eed4572f1
Revises: 4651cf305aab
Create Date: 2022-09-30 20:56:03.511620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a9eed4572f1'
down_revision = '4651cf305aab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rig_band',
    sa.Column('rig_id', sa.Integer(), nullable=True),
    sa.Column('band_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['band_id'], ['band.id'], name=op.f('fk_rig_band_band_id_band')),
    sa.ForeignKeyConstraint(['rig_id'], ['rig.id'], name=op.f('fk_rig_band_rig_id_rig'))
    )
    op.create_table('event_config',
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('config_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['configuration.id'], name=op.f('fk_event_config_config_id_configuration')),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_event_config_event_id_event'))
    )
    op.drop_table('post_tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tag',
    sa.Column('rig_id', sa.INTEGER(), nullable=True),
    sa.Column('band_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['band_id'], ['band.id'], name='fk_post_tag_band_id_band'),
    sa.ForeignKeyConstraint(['rig_id'], ['rig.id'], name='fk_post_tag_rig_id_rig')
    )
    op.drop_table('event_config')
    op.drop_table('rig_band')
    # ### end Alembic commands ###
