"""empty message

Revision ID: 0d2dc03ff1c0
Revises: 1b552a1864da
Create Date: 2022-09-07 11:11:05.556703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d2dc03ff1c0'
down_revision = '1b552a1864da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('QSO', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vucc_grids', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('my_vucc_grids', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('usaca_counties', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('my_usaca_counties', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('my_state', sa.String(length=25), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('QSO', schema=None) as batch_op:
        batch_op.drop_column('my_state')
        batch_op.drop_column('state')
        batch_op.drop_column('my_usaca_counties')
        batch_op.drop_column('usaca_counties')
        batch_op.drop_column('my_vucc_grids')
        batch_op.drop_column('vucc_grids')

    # ### end Alembic commands ###
