"""empty message

Revision ID: 11db0a1d305d
Revises: 7e15b5f6fcd1
Create Date: 2023-06-08 22:26:41.178300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11db0a1d305d'
down_revision = '7e15b5f6fcd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('my_gridsquare', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('my_gridsquare')

    # ### end Alembic commands ###
