"""empty message

Revision ID: 1b552a1864da
Revises: 3702381a3ef5
Create Date: 2022-09-06 16:20:38.782028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b552a1864da'
down_revision = '3702381a3ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('QSO', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sig', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('my_sig', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sig_info', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('my_sig_info', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('QSO', schema=None) as batch_op:
        batch_op.drop_column('my_sig_info')
        batch_op.drop_column('sig_info')
        batch_op.drop_column('my_sig')
        batch_op.drop_column('sig')

    # ### end Alembic commands ###
