"""empty message

Revision ID: 3702381a3ef5
Revises: c6f4dcddaf4b
Create Date: 2022-09-06 11:47:19.824121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3702381a3ef5'
down_revision = 'c6f4dcddaf4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('QSO', schema=None) as batch_op:
        batch_op.add_column(sa.Column('my_street', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('QSO', schema=None) as batch_op:
        batch_op.drop_column('my_street')

    # ### end Alembic commands ###
