"""empty message

Revision ID: 3d4257394bf5
Revises: 714faed1086f
Create Date: 2023-04-10 15:11:17.828026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d4257394bf5'
down_revision = '714faed1086f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qsoevent', schema=None) as batch_op:
        batch_op.alter_column('event',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('qso',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qsoevent', schema=None) as batch_op:
        batch_op.alter_column('qso',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('event',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
