"""empty message

Revision ID: 40c4e0ef289f
Revises: 0d2dc03ff1c0
Create Date: 2022-09-07 14:31:08.373200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40c4e0ef289f'
down_revision = '0d2dc03ff1c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('QSO', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rig', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('antenna', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('QSO', schema=None) as batch_op:
        batch_op.drop_column('antenna')
        batch_op.drop_column('rig')

    # ### end Alembic commands ###
