"""empty message

Revision ID: 41b6731d06c3
Revises: 17eae088ada5
Create Date: 2022-09-02 22:15:57.889083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41b6731d06c3'
down_revision = '17eae088ada5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('QSO', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qslrdate', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('qslsdate', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('lotw_qslrdate', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('eqsl_qslrdate', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('contest_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('QSO', schema=None) as batch_op:
        batch_op.drop_column('contest_id')
        batch_op.drop_column('eqsl_qslrdate')
        batch_op.drop_column('lotw_qslrdate')
        batch_op.drop_column('qslsdate')
        batch_op.drop_column('qslrdate')

    # ### end Alembic commands ###
