"""empty message

Revision ID: 4651cf305aab
Revises: a0322792e12c
Create Date: 2022-09-27 12:02:27.575959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4651cf305aab'
down_revision = 'a0322792e12c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('antenna', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manufacturer', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('comment', sa.String(length=255), nullable=True))

    with op.batch_alter_table('rig', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manufacturer', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('comment', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rig', schema=None) as batch_op:
        batch_op.drop_column('comment')
        batch_op.drop_column('manufacturer')

    with op.batch_alter_table('antenna', schema=None) as batch_op:
        batch_op.drop_column('comment')
        batch_op.drop_column('manufacturer')

    # ### end Alembic commands ###
