"""empty message

Revision ID: 494e532c0d96
Revises: d389604154e2
Create Date: 2022-08-31 16:49:01.009016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '494e532c0d96'
down_revision = 'd389604154e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('QSO', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('my_country', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('distance', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('dxcc', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('my_dxcc', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('my_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('my_city', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cqz', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('my_cq_zone', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ituz', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('my_itu_zone', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qsl_rcvd', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('qsl_rcvd_via', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('qsl_sent', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('qsl_sent_via', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('lotw_qsl_rcvd', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('lotw_qsl_sent', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('lotw_qslsdate', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('eqsl_qsl_rcvd', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('eqsl_qsl_sent', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('eqsl_qslsdate', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('qrzcom_qso_upload_status', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('qrzcom_qso_upload_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('a_index', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('k_index', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sfi', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ant_az', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ant_el', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comment', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cont', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cnty', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('my_cnty', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('my_postal_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('qth', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('swl', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('lat', sa.String(length=11), nullable=True))
        batch_op.add_column(sa.Column('my_lat', sa.String(length=11), nullable=True))
        batch_op.add_column(sa.Column('lon', sa.String(length=11), nullable=True))
        batch_op.add_column(sa.Column('my_lon', sa.String(length=11), nullable=True))
        batch_op.add_column(sa.Column('pfx', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('QSO', schema=None) as batch_op:
        batch_op.drop_column('pfx')
        batch_op.drop_column('my_lon')
        batch_op.drop_column('lon')
        batch_op.drop_column('my_lat')
        batch_op.drop_column('lat')
        batch_op.drop_column('swl')
        batch_op.drop_column('qth')
        batch_op.drop_column('my_postal_code')
        batch_op.drop_column('my_cnty')
        batch_op.drop_column('cnty')
        batch_op.drop_column('email')
        batch_op.drop_column('cont')
        batch_op.drop_column('comment')
        batch_op.drop_column('ant_el')
        batch_op.drop_column('ant_az')
        batch_op.drop_column('sfi')
        batch_op.drop_column('k_index')
        batch_op.drop_column('a_index')
        batch_op.drop_column('address')
        batch_op.drop_column('qrzcom_qso_upload_date')
        batch_op.drop_column('qrzcom_qso_upload_status')
        batch_op.drop_column('eqsl_qslsdate')
        batch_op.drop_column('eqsl_qsl_sent')
        batch_op.drop_column('eqsl_qsl_rcvd')
        batch_op.drop_column('lotw_qslsdate')
        batch_op.drop_column('lotw_qsl_sent')
        batch_op.drop_column('lotw_qsl_rcvd')
        batch_op.drop_column('qsl_sent_via')
        batch_op.drop_column('qsl_sent')
        batch_op.drop_column('qsl_rcvd_via')
        batch_op.drop_column('qsl_rcvd')
        batch_op.drop_column('my_itu_zone')
        batch_op.drop_column('ituz')
        batch_op.drop_column('my_cq_zone')
        batch_op.drop_column('cqz')
        batch_op.drop_column('my_city')
        batch_op.drop_column('my_name')
        batch_op.drop_column('name')
        batch_op.drop_column('my_dxcc')
        batch_op.drop_column('dxcc')
        batch_op.drop_column('distance')
        batch_op.drop_column('my_country')
        batch_op.drop_column('country')

    # ### end Alembic commands ###
