"""more callsigns.

Revision ID: 5e8e3201ab51
Revises: 28a8f318e77d
Create Date: 2023-03-09 21:11:47.514119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e8e3201ab51'
down_revision = '28a8f318e77d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('QSO', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contacted_op', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('eq_call', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('QSO', schema=None) as batch_op:
        batch_op.drop_column('eq_call')
        batch_op.drop_column('contacted_op')

    # ### end Alembic commands ###
