"""empty message

Revision ID: 6ae1f21c96be
Revises: f8e4418ace0d
Create Date: 2022-09-22 22:49:54.282901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ae1f21c96be'
down_revision = 'f8e4418ace0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('band',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_band')),
    sa.UniqueConstraint('name', name=op.f('uq_band_name'))
    )
    op.create_table('antenna',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_antenna_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_antenna')),
    sa.UniqueConstraint('name', name=op.f('uq_antenna_name'))
    )
    op.create_table('rig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_rig_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rig')),
    sa.UniqueConstraint('name', name=op.f('uq_rig_name'))
    )
    op.create_table('configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('antenna', sa.Integer(), nullable=True),
    sa.Column('rig_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['antenna'], ['antenna.id'], name=op.f('fk_configuration_antenna_antenna')),
    sa.ForeignKeyConstraint(['rig_id'], ['rig.id'], name=op.f('fk_configuration_rig_id_rig')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_configuration_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configuration')),
    sa.UniqueConstraint('name', name=op.f('uq_configuration_name'))
    )
    op.create_table('post_tag',
    sa.Column('rig_id', sa.Integer(), nullable=True),
    sa.Column('band_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['band_id'], ['band.id'], name=op.f('fk_post_tag_band_id_band')),
    sa.ForeignKeyConstraint(['rig_id'], ['rig.id'], name=op.f('fk_post_tag_rig_id_rig'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tag')
    op.drop_table('configuration')
    op.drop_table('rig')
    op.drop_table('antenna')
    op.drop_table('band')
    # ### end Alembic commands ###
