"""Initial migration.

Revision ID: 7e5522e73e7b
Revises: 
Create Date: 2023-03-04 18:30:50.388716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e5522e73e7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('QSO', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precedence', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('check', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contest_class', sa.String(length=25), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('QSO', schema=None) as batch_op:
        batch_op.drop_column('contest_class')
        batch_op.drop_column('check')
        batch_op.drop_column('precedence')

    # ### end Alembic commands ###
