"""empty message

Revision ID: 82254a0a67ef
Revises: 494e532c0d96
Create Date: 2022-08-31 23:27:27.888315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82254a0a67ef'
down_revision = '494e532c0d96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('QSO', schema=None) as batch_op:
        batch_op.add_column(sa.Column('band_rx', sa.String(length=25), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('QSO', schema=None) as batch_op:
        batch_op.drop_column('band_rx')

    # ### end Alembic commands ###
