"""empty message

Revision ID: 84e75bea4089
Revises: dea270652710
Create Date: 2023-03-18 21:05:44.552897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84e75bea4089'
down_revision = 'dea270652710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    with op.batch_alter_table('rig_band', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rig_band', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('event_config', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
