"""empty message

Revision ID: 97e09985f3a8
Revises: 
Create Date: 2022-09-08 13:54:59.253692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97e09985f3a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_callsign')
    with op.batch_alter_table('callsign', schema=None) as batch_op:
        batch_op.drop_constraint('callsign', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_callsign_name'), ['name'])

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qso_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_event_name'), ['name'])
        #batch_op.drop_constraint('fk_event_user_id_QSO', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_event_qso_id_QSO'), 'QSO', ['qso_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_event_user_id_user'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('callsign', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_name'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')
        batch_op.create_unique_constraint('callsign', ['name'])

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_event_user_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_event_qso_id_QSO'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'QSO', ['user_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_event_name'), type_='unique')
        batch_op.drop_column('qso_id')

    with op.batch_alter_table('callsign', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_callsign_name'), type_='unique')
        batch_op.create_unique_constraint('callsign', ['name'])

    op.create_table('_alembic_tmp_callsign',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('primary', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_callsign_name')
    )
    # ### end Alembic commands ###
