"""empty message

Revision ID: a0322792e12c
Revises: a2892e687b85
Create Date: 2022-09-23 17:38:11.899688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0322792e12c'
down_revision = 'a2892e687b85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('QSO', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_QSO_config_id_configuration'), 'configuration', ['config_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('QSO', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_QSO_config_id_configuration'), type_='foreignkey')
        batch_op.drop_column('config_id')

    # ### end Alembic commands ###
