"""empty message

Revision ID: a2892e687b85
Revises: 5d885312dec5
Create Date: 2022-09-23 13:32:30.266176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2892e687b85'
down_revision = '5d885312dec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('antenna_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_configuration_antenna_antenna', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_configuration_antenna_id_antenna'), 'antenna', ['antenna_id'], ['id'])
        batch_op.drop_column('antenna')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('antenna', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_configuration_antenna_id_antenna'), type_='foreignkey')
        batch_op.create_foreign_key('fk_configuration_antenna_antenna', 'antenna', ['antenna'], ['id'])
        batch_op.drop_column('antenna_id')

    # ### end Alembic commands ###
