"""empty message

Revision ID: ab2f4620351e
Revises: 
Create Date: 2023-02-28 22:55:44.167080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab2f4620351e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('band',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_band')),
    sa.UniqueConstraint('name', name=op.f('uq_band_name'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('name', name=op.f('uq_user_name'))
    )
    op.create_table('antenna',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_antenna_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_antenna')),
    sa.UniqueConstraint('name', name=op.f('uq_antenna_name'))
    )
    op.create_table('callsign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('primary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_callsign_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_callsign')),
    sa.UniqueConstraint('name', name=op.f('uq_callsign_name'))
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('type', sa.String(length=15), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_event_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event')),
    sa.UniqueConstraint('name', name=op.f('uq_event_name'))
    )
    op.create_table('rig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_rig_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rig')),
    sa.UniqueConstraint('name', name=op.f('uq_rig_name'))
    )
    op.create_table('configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('antenna_id', sa.Integer(), nullable=True),
    sa.Column('rig_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['antenna_id'], ['antenna.id'], name=op.f('fk_configuration_antenna_id_antenna')),
    sa.ForeignKeyConstraint(['rig_id'], ['rig.id'], name=op.f('fk_configuration_rig_id_rig')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_configuration_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configuration')),
    sa.UniqueConstraint('name', name=op.f('uq_configuration_name'))
    )
    op.create_table('rig_band',
    sa.Column('rig_id', sa.Integer(), nullable=True),
    sa.Column('band_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['band_id'], ['band.id'], name=op.f('fk_rig_band_band_id_band')),
    sa.ForeignKeyConstraint(['rig_id'], ['rig.id'], name=op.f('fk_rig_band_rig_id_rig'))
    )
    op.create_table('QSO',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('band', sa.String(length=25), nullable=True),
    sa.Column('band_rx', sa.String(length=25), nullable=True),
    sa.Column('mode', sa.String(length=25), nullable=True),
    sa.Column('submode', sa.String(length=25), nullable=True),
    sa.Column('freq', sa.String(length=25), nullable=True),
    sa.Column('freq_rx', sa.String(length=25), nullable=True),
    sa.Column('call', sa.String(length=50), nullable=True),
    sa.Column('station_callsign', sa.String(length=50), nullable=True),
    sa.Column('operator', sa.String(length=50), nullable=True),
    sa.Column('owner_callsign', sa.String(length=50), nullable=True),
    sa.Column('qso_date', sa.Date(), nullable=True),
    sa.Column('qso_date_off', sa.Date(), nullable=True),
    sa.Column('time_on', sa.Time(), nullable=True),
    sa.Column('time_off', sa.Time(), nullable=True),
    sa.Column('gridsquare', sa.String(length=10), nullable=True),
    sa.Column('my_gridsquare', sa.String(length=10), nullable=True),
    sa.Column('rst_rcvd', sa.String(length=10), nullable=True),
    sa.Column('rst_sent', sa.String(length=10), nullable=True),
    sa.Column('tx_pwr', sa.String(length=10), nullable=True),
    sa.Column('my_rig', sa.String(length=100), nullable=True),
    sa.Column('my_antenna', sa.String(length=100), nullable=True),
    sa.Column('qso_random', sa.String(length=1), nullable=True),
    sa.Column('qso_complete', sa.String(length=3), nullable=True),
    sa.Column('sat_mode', sa.String(length=25), nullable=True),
    sa.Column('sat_name', sa.String(length=25), nullable=True),
    sa.Column('srx', sa.Integer(), nullable=True),
    sa.Column('srx_string', sa.String(length=50), nullable=True),
    sa.Column('stx', sa.Integer(), nullable=True),
    sa.Column('stx_string', sa.String(length=50), nullable=True),
    sa.Column('my_sota_ref', sa.String(length=25), nullable=True),
    sa.Column('sota_ref', sa.String(length=25), nullable=True),
    sa.Column('my_iota', sa.String(length=6), nullable=True),
    sa.Column('iota', sa.String(length=6), nullable=True),
    sa.Column('my_iota_island_id', sa.Integer(), nullable=True),
    sa.Column('iota_island_id', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('my_country', sa.String(length=50), nullable=True),
    sa.Column('distance', sa.String(length=10), nullable=True),
    sa.Column('dxcc', sa.Integer(), nullable=True),
    sa.Column('my_dxcc', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('my_name', sa.String(length=50), nullable=True),
    sa.Column('my_city', sa.String(length=50), nullable=True),
    sa.Column('cqz', sa.Integer(), nullable=True),
    sa.Column('my_cq_zone', sa.Integer(), nullable=True),
    sa.Column('ituz', sa.Integer(), nullable=True),
    sa.Column('my_itu_zone', sa.Integer(), nullable=True),
    sa.Column('qsl_rcvd', sa.String(length=3), nullable=True),
    sa.Column('qsl_rcvd_via', sa.String(length=3), nullable=True),
    sa.Column('qsl_sent', sa.String(length=3), nullable=True),
    sa.Column('qsl_sent_via', sa.String(length=3), nullable=True),
    sa.Column('qslrdate', sa.Date(), nullable=True),
    sa.Column('qslsdate', sa.Date(), nullable=True),
    sa.Column('lotw_qsl_rcvd', sa.String(length=3), nullable=True),
    sa.Column('lotw_qsl_sent', sa.String(length=3), nullable=True),
    sa.Column('lotw_qslsdate', sa.Date(), nullable=True),
    sa.Column('lotw_qslrdate', sa.Date(), nullable=True),
    sa.Column('eqsl_qsl_rcvd', sa.String(length=3), nullable=True),
    sa.Column('eqsl_qsl_sent', sa.String(length=3), nullable=True),
    sa.Column('eqsl_qslsdate', sa.Date(), nullable=True),
    sa.Column('eqsl_qslrdate', sa.Date(), nullable=True),
    sa.Column('qrzcom_qso_upload_status', sa.String(length=3), nullable=True),
    sa.Column('qrzcom_qso_upload_date', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('a_index', sa.Integer(), nullable=True),
    sa.Column('k_index', sa.Integer(), nullable=True),
    sa.Column('sfi', sa.Integer(), nullable=True),
    sa.Column('ant_az', sa.Integer(), nullable=True),
    sa.Column('ant_el', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('cont', sa.String(length=2), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('cnty', sa.String(length=50), nullable=True),
    sa.Column('my_cnty', sa.String(length=50), nullable=True),
    sa.Column('my_postal_code', sa.String(length=10), nullable=True),
    sa.Column('qth', sa.String(length=50), nullable=True),
    sa.Column('swl', sa.String(length=2), nullable=True),
    sa.Column('lat', sa.String(length=11), nullable=True),
    sa.Column('my_lat', sa.String(length=11), nullable=True),
    sa.Column('lon', sa.String(length=11), nullable=True),
    sa.Column('my_lon', sa.String(length=11), nullable=True),
    sa.Column('pfx', sa.String(length=15), nullable=True),
    sa.Column('contest_id', sa.String(length=50), nullable=True),
    sa.Column('my_wwff_ref', sa.String(length=15), nullable=True),
    sa.Column('wwff_ref', sa.String(length=15), nullable=True),
    sa.Column('my_street', sa.String(length=50), nullable=True),
    sa.Column('sig', sa.String(length=50), nullable=True),
    sa.Column('my_sig', sa.String(length=50), nullable=True),
    sa.Column('sig_info', sa.String(length=50), nullable=True),
    sa.Column('my_sig_info', sa.String(length=50), nullable=True),
    sa.Column('vucc_grids', sa.String(length=25), nullable=True),
    sa.Column('my_vucc_grids', sa.String(length=25), nullable=True),
    sa.Column('usaca_counties', sa.String(length=50), nullable=True),
    sa.Column('my_usaca_counties', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=25), nullable=True),
    sa.Column('my_state', sa.String(length=25), nullable=True),
    sa.Column('rig', sa.String(length=50), nullable=True),
    sa.Column('import_source', sa.String(length=255), nullable=True),
    sa.Column('import_date', sa.Date(), nullable=True),
    sa.Column('import_comments', sa.String(length=2000), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('config_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['configuration.id'], name=op.f('fk_QSO_config_id_configuration')),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_QSO_event_id_event')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_QSO'))
    )
    op.create_table('event_config',
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('config_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['configuration.id'], name=op.f('fk_event_config_config_id_configuration')),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_event_config_event_id_event'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_config')
    op.drop_table('QSO')
    op.drop_table('rig_band')
    op.drop_table('configuration')
    op.drop_table('rig')
    op.drop_table('event')
    op.drop_table('callsign')
    op.drop_table('antenna')
    op.drop_table('user')
    op.drop_table('band')
    # ### end Alembic commands ###
