"""empty message

Revision ID: c2fb5be211a5
Revises: 97e09985f3a8
Create Date: 2022-09-09 23:21:22.433526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2fb5be211a5'
down_revision = '97e09985f3a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('qso_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('qso_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
