"""empty message

Revision ID: c6f4dcddaf4b
Revises: 41b6731d06c3
Create Date: 2022-09-06 10:16:49.753807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6f4dcddaf4b'
down_revision = '41b6731d06c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('QSO', schema=None) as batch_op:
        batch_op.add_column(sa.Column('my_wwff_ref', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('wwff_ref', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('QSO', schema=None) as batch_op:
        batch_op.drop_column('wwff_ref')
        batch_op.drop_column('my_wwff_ref')

    # ### end Alembic commands ###
