"""empty message

Revision ID: d389604154e2
Revises: c3719a7d95bb
Create Date: 2022-08-30 14:44:04.215016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd389604154e2'
down_revision = 'c3719a7d95bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('callsign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint('callsign', ['name'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('callsign', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('callsign', schema=None) as batch_op:
        batch_op.drop_constraint('callsign', type_='unique')
        batch_op.drop_column('primary')

    # ### end Alembic commands ###
