"""POTA added to db

Revision ID: dea270652710
Revises: 5e8e3201ab51
Create Date: 2023-03-14 21:07:00.971544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dea270652710'
down_revision = '5e8e3201ab51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('QSO', schema=None) as batch_op:
        batch_op.add_column(sa.Column('my_pota_ref', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('pota_ref', sa.String(length=25), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('QSO', schema=None) as batch_op:
        batch_op.drop_column('pota_ref')
        batch_op.drop_column('my_pota_ref')

    # ### end Alembic commands ###
