"""empty message

Revision ID: f8e4418ace0d
Revises: c2fb5be211a5
Create Date: 2022-09-10 14:58:04.199653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8e4418ace0d'
down_revision = 'c2fb5be211a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('QSO', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_QSO_event_id_event'), 'event', ['event_id'], ['id'])

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('qso_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qso_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'QSO', ['qso_id'], ['id'])

    with op.batch_alter_table('QSO', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_QSO_event_id_event'), type_='foreignkey')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###
