"""empty message

Revision ID: f8eaf753a881
Revises: 84e75bea4089
Create Date: 2023-03-23 11:13:44.187847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8eaf753a881'
down_revision = '84e75bea4089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sota_ref', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('pota_ref', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('wwff_ref', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('iota_ref', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sat_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('square', sa.String(length=4), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('square')
        batch_op.drop_column('sat_name')
        batch_op.drop_column('iota_ref')
        batch_op.drop_column('wwff_ref')
        batch_op.drop_column('pota_ref')
        batch_op.drop_column('sota_ref')

    # ### end Alembic commands ###
